name: Merge to dev
on:
  pull_request:
    types: [labeled]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dev
      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.1.0
        with:
          label_name: 'feature'
          target_branch: 'dev'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
